// Generated by jextract

package dmacd.clay.demo;

import dmacd.ffm.clay.Clay_String;

import java.lang.foreign.*;
import java.util.function.*;

import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct {
 *     Clay_String title;
 *     Clay_String contents;
 * }
 * }
 */
public class Document {

    Document() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        Clay_String.layout().withName("title"),
        Clay_String.layout().withName("contents")
    ).withName("$anon$3:10");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final GroupLayout title$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("title"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * Clay_String title
     * }
     */
    public static final GroupLayout title$layout() {
        return title$LAYOUT;
    }

    private static final long title$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * Clay_String title
     * }
     */
    public static final long title$offset() {
        return title$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * Clay_String title
     * }
     */
    public static MemorySegment title(MemorySegment struct) {
        return struct.asSlice(title$OFFSET, title$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * Clay_String title
     * }
     */
    public static void title(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, title$OFFSET, title$LAYOUT.byteSize());
    }

    private static final GroupLayout contents$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("contents"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * Clay_String contents
     * }
     */
    public static final GroupLayout contents$layout() {
        return contents$LAYOUT;
    }

    private static final long contents$OFFSET = 16;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * Clay_String contents
     * }
     */
    public static final long contents$offset() {
        return contents$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * Clay_String contents
     * }
     */
    public static MemorySegment contents(MemorySegment struct) {
        return struct.asSlice(contents$OFFSET, contents$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * Clay_String contents
     * }
     */
    public static void contents(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, contents$OFFSET, contents$LAYOUT.byteSize());
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

