// Generated by jextract

package dmacd.ffm.clay;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct Clay_ClipElementConfig {
 *     bool horizontal;
 *     bool vertical;
 *     Clay_Vector2 childOffset;
 * }
 * }
 */
public class Clay_ClipElementConfig {

    Clay_ClipElementConfig() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        ClayFFM.C_BOOL.withName("horizontal"),
        ClayFFM.C_BOOL.withName("vertical"),
        MemoryLayout.paddingLayout(2),
        Clay_Vector2.layout().withName("childOffset")
    ).withName("Clay_ClipElementConfig");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfBoolean horizontal$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("horizontal"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * bool horizontal
     * }
     */
    public static final OfBoolean horizontal$layout() {
        return horizontal$LAYOUT;
    }

    private static final long horizontal$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * bool horizontal
     * }
     */
    public static final long horizontal$offset() {
        return horizontal$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * bool horizontal
     * }
     */
    public static boolean horizontal(MemorySegment struct) {
        return struct.get(horizontal$LAYOUT, horizontal$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * bool horizontal
     * }
     */
    public static void horizontal(MemorySegment struct, boolean fieldValue) {
        struct.set(horizontal$LAYOUT, horizontal$OFFSET, fieldValue);
    }

    private static final OfBoolean vertical$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("vertical"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * bool vertical
     * }
     */
    public static final OfBoolean vertical$layout() {
        return vertical$LAYOUT;
    }

    private static final long vertical$OFFSET = 1;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * bool vertical
     * }
     */
    public static final long vertical$offset() {
        return vertical$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * bool vertical
     * }
     */
    public static boolean vertical(MemorySegment struct) {
        return struct.get(vertical$LAYOUT, vertical$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * bool vertical
     * }
     */
    public static void vertical(MemorySegment struct, boolean fieldValue) {
        struct.set(vertical$LAYOUT, vertical$OFFSET, fieldValue);
    }

    private static final GroupLayout childOffset$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("childOffset"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * Clay_Vector2 childOffset
     * }
     */
    public static final GroupLayout childOffset$layout() {
        return childOffset$LAYOUT;
    }

    private static final long childOffset$OFFSET = 4;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * Clay_Vector2 childOffset
     * }
     */
    public static final long childOffset$offset() {
        return childOffset$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * Clay_Vector2 childOffset
     * }
     */
    public static MemorySegment childOffset(MemorySegment struct) {
        return struct.asSlice(childOffset$OFFSET, childOffset$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * Clay_Vector2 childOffset
     * }
     */
    public static void childOffset(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, childOffset$OFFSET, childOffset$LAYOUT.byteSize());
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

