// Generated by jextract

package dmacd.ffm.clay;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct Clay_StringSlice {
 *     int32_t length;
 *     const char *chars;
 *     const char *baseChars;
 * }
 * }
 */
public class Clay_StringSlice {

    Clay_StringSlice() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        ClayFFM.C_INT.withName("length"),
        MemoryLayout.paddingLayout(4),
        ClayFFM.C_POINTER.withName("chars"),
        ClayFFM.C_POINTER.withName("baseChars")
    ).withName("Clay_StringSlice");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt length$LAYOUT = (OfInt)$LAYOUT.select(groupElement("length"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int32_t length
     * }
     */
    public static final OfInt length$layout() {
        return length$LAYOUT;
    }

    private static final long length$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int32_t length
     * }
     */
    public static final long length$offset() {
        return length$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int32_t length
     * }
     */
    public static int length(MemorySegment struct) {
        return struct.get(length$LAYOUT, length$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int32_t length
     * }
     */
    public static void length(MemorySegment struct, int fieldValue) {
        struct.set(length$LAYOUT, length$OFFSET, fieldValue);
    }

    private static final AddressLayout chars$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("chars"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const char *chars
     * }
     */
    public static final AddressLayout chars$layout() {
        return chars$LAYOUT;
    }

    private static final long chars$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const char *chars
     * }
     */
    public static final long chars$offset() {
        return chars$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const char *chars
     * }
     */
    public static MemorySegment chars(MemorySegment struct) {
        return struct.get(chars$LAYOUT, chars$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const char *chars
     * }
     */
    public static void chars(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(chars$LAYOUT, chars$OFFSET, fieldValue);
    }

    private static final AddressLayout baseChars$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("baseChars"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const char *baseChars
     * }
     */
    public static final AddressLayout baseChars$layout() {
        return baseChars$LAYOUT;
    }

    private static final long baseChars$OFFSET = 16;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const char *baseChars
     * }
     */
    public static final long baseChars$offset() {
        return baseChars$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const char *baseChars
     * }
     */
    public static MemorySegment baseChars(MemorySegment struct) {
        return struct.get(baseChars$LAYOUT, baseChars$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const char *baseChars
     * }
     */
    public static void baseChars(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(baseChars$LAYOUT, baseChars$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

