// Generated by jextract

package dmacd.ffm.clay;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct Clay_CustomElementConfig {
 *     void *customData;
 * }
 * }
 */
public class Clay_CustomElementConfig {

    Clay_CustomElementConfig() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        ClayFFM.C_POINTER.withName("customData")
    ).withName("Clay_CustomElementConfig");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout customData$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("customData"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void *customData
     * }
     */
    public static final AddressLayout customData$layout() {
        return customData$LAYOUT;
    }

    private static final long customData$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void *customData
     * }
     */
    public static final long customData$offset() {
        return customData$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void *customData
     * }
     */
    public static MemorySegment customData(MemorySegment struct) {
        return struct.get(customData$LAYOUT, customData$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void *customData
     * }
     */
    public static void customData(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(customData$LAYOUT, customData$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

