// Generated by jextract

package dmacd.ffm.clay;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct Clay_ImageRenderData {
 *     Clay_Color backgroundColor;
 *     Clay_CornerRadius cornerRadius;
 *     void *imageData;
 * }
 * }
 */
public class Clay_ImageRenderData {

    Clay_ImageRenderData() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        Clay_Color.layout().withName("backgroundColor"),
        Clay_CornerRadius.layout().withName("cornerRadius"),
        ClayFFM.C_POINTER.withName("imageData")
    ).withName("Clay_ImageRenderData");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final GroupLayout backgroundColor$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("backgroundColor"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * Clay_Color backgroundColor
     * }
     */
    public static final GroupLayout backgroundColor$layout() {
        return backgroundColor$LAYOUT;
    }

    private static final long backgroundColor$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * Clay_Color backgroundColor
     * }
     */
    public static final long backgroundColor$offset() {
        return backgroundColor$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * Clay_Color backgroundColor
     * }
     */
    public static MemorySegment backgroundColor(MemorySegment struct) {
        return struct.asSlice(backgroundColor$OFFSET, backgroundColor$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * Clay_Color backgroundColor
     * }
     */
    public static void backgroundColor(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, backgroundColor$OFFSET, backgroundColor$LAYOUT.byteSize());
    }

    private static final GroupLayout cornerRadius$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("cornerRadius"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * Clay_CornerRadius cornerRadius
     * }
     */
    public static final GroupLayout cornerRadius$layout() {
        return cornerRadius$LAYOUT;
    }

    private static final long cornerRadius$OFFSET = 16;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * Clay_CornerRadius cornerRadius
     * }
     */
    public static final long cornerRadius$offset() {
        return cornerRadius$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * Clay_CornerRadius cornerRadius
     * }
     */
    public static MemorySegment cornerRadius(MemorySegment struct) {
        return struct.asSlice(cornerRadius$OFFSET, cornerRadius$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * Clay_CornerRadius cornerRadius
     * }
     */
    public static void cornerRadius(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, cornerRadius$OFFSET, cornerRadius$LAYOUT.byteSize());
    }

    private static final AddressLayout imageData$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("imageData"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void *imageData
     * }
     */
    public static final AddressLayout imageData$layout() {
        return imageData$LAYOUT;
    }

    private static final long imageData$OFFSET = 32;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void *imageData
     * }
     */
    public static final long imageData$offset() {
        return imageData$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void *imageData
     * }
     */
    public static MemorySegment imageData(MemorySegment struct) {
        return struct.get(imageData$LAYOUT, imageData$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void *imageData
     * }
     */
    public static void imageData(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(imageData$LAYOUT, imageData$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

