// Generated by jextract

package dmacd.ffm.clay;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct Clay_Arena {
 *     uintptr_t nextAllocation;
 *     size_t capacity;
 *     char *memory;
 * }
 * }
 */
public class Clay_Arena {

    Clay_Arena() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        ClayFFM.C_LONG_LONG.withName("nextAllocation"),
        ClayFFM.C_LONG_LONG.withName("capacity"),
        ClayFFM.C_POINTER.withName("memory")
    ).withName("Clay_Arena");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfLong nextAllocation$LAYOUT = (OfLong)$LAYOUT.select(groupElement("nextAllocation"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uintptr_t nextAllocation
     * }
     */
    public static final OfLong nextAllocation$layout() {
        return nextAllocation$LAYOUT;
    }

    private static final long nextAllocation$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uintptr_t nextAllocation
     * }
     */
    public static final long nextAllocation$offset() {
        return nextAllocation$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uintptr_t nextAllocation
     * }
     */
    public static long nextAllocation(MemorySegment struct) {
        return struct.get(nextAllocation$LAYOUT, nextAllocation$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uintptr_t nextAllocation
     * }
     */
    public static void nextAllocation(MemorySegment struct, long fieldValue) {
        struct.set(nextAllocation$LAYOUT, nextAllocation$OFFSET, fieldValue);
    }

    private static final OfLong capacity$LAYOUT = (OfLong)$LAYOUT.select(groupElement("capacity"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * size_t capacity
     * }
     */
    public static final OfLong capacity$layout() {
        return capacity$LAYOUT;
    }

    private static final long capacity$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * size_t capacity
     * }
     */
    public static final long capacity$offset() {
        return capacity$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * size_t capacity
     * }
     */
    public static long capacity(MemorySegment struct) {
        return struct.get(capacity$LAYOUT, capacity$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * size_t capacity
     * }
     */
    public static void capacity(MemorySegment struct, long fieldValue) {
        struct.set(capacity$LAYOUT, capacity$OFFSET, fieldValue);
    }

    private static final AddressLayout memory$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("memory"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * char *memory
     * }
     */
    public static final AddressLayout memory$layout() {
        return memory$LAYOUT;
    }

    private static final long memory$OFFSET = 16;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * char *memory
     * }
     */
    public static final long memory$offset() {
        return memory$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * char *memory
     * }
     */
    public static MemorySegment memory(MemorySegment struct) {
        return struct.get(memory$LAYOUT, memory$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * char *memory
     * }
     */
    public static void memory(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(memory$LAYOUT, memory$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

