// Generated by jextract

package dmacd.clay.demo.ffm;

import java.lang.foreign.*;
import java.util.function.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct {
 *     int32_t selectedDocumentIndex;
 *     float yOffset;
 *     ClayVideoDemo_Arena frameArena;
 * }
 * }
 */
public class ClayVideoDemo_Data {

    ClayVideoDemo_Data() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        DemoFFM.C_INT.withName("selectedDocumentIndex"),
        DemoFFM.C_FLOAT.withName("yOffset"),
        ClayVideoDemo_Arena.layout().withName("frameArena")
    ).withName("$anon$18:10");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt selectedDocumentIndex$LAYOUT = (OfInt)$LAYOUT.select(groupElement("selectedDocumentIndex"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int32_t selectedDocumentIndex
     * }
     */
    public static final OfInt selectedDocumentIndex$layout() {
        return selectedDocumentIndex$LAYOUT;
    }

    private static final long selectedDocumentIndex$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int32_t selectedDocumentIndex
     * }
     */
    public static final long selectedDocumentIndex$offset() {
        return selectedDocumentIndex$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int32_t selectedDocumentIndex
     * }
     */
    public static int selectedDocumentIndex(MemorySegment struct) {
        return struct.get(selectedDocumentIndex$LAYOUT, selectedDocumentIndex$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int32_t selectedDocumentIndex
     * }
     */
    public static void selectedDocumentIndex(MemorySegment struct, int fieldValue) {
        struct.set(selectedDocumentIndex$LAYOUT, selectedDocumentIndex$OFFSET, fieldValue);
    }

    private static final OfFloat yOffset$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("yOffset"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float yOffset
     * }
     */
    public static final OfFloat yOffset$layout() {
        return yOffset$LAYOUT;
    }

    private static final long yOffset$OFFSET = 4;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float yOffset
     * }
     */
    public static final long yOffset$offset() {
        return yOffset$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float yOffset
     * }
     */
    public static float yOffset(MemorySegment struct) {
        return struct.get(yOffset$LAYOUT, yOffset$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float yOffset
     * }
     */
    public static void yOffset(MemorySegment struct, float fieldValue) {
        struct.set(yOffset$LAYOUT, yOffset$OFFSET, fieldValue);
    }

    private static final GroupLayout frameArena$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("frameArena"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * ClayVideoDemo_Arena frameArena
     * }
     */
    public static final GroupLayout frameArena$layout() {
        return frameArena$LAYOUT;
    }

    private static final long frameArena$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * ClayVideoDemo_Arena frameArena
     * }
     */
    public static final long frameArena$offset() {
        return frameArena$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * ClayVideoDemo_Arena frameArena
     * }
     */
    public static MemorySegment frameArena(MemorySegment struct) {
        return struct.asSlice(frameArena$OFFSET, frameArena$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * ClayVideoDemo_Arena frameArena
     * }
     */
    public static void frameArena(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, frameArena$OFFSET, frameArena$LAYOUT.byteSize());
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

