// Generated by jextract

package dmacd.clay.demo.ffm;

import java.lang.foreign.*;
import java.util.function.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct {
 *     int32_t requestedDocumentIndex;
 *     int32_t *selectedDocumentIndex;
 * }
 * }
 */
public class SidebarClickData {

    SidebarClickData() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        DemoFFM.C_INT.withName("requestedDocumentIndex"),
        MemoryLayout.paddingLayout(4),
        DemoFFM.C_POINTER.withName("selectedDocumentIndex")
    ).withName("$anon$24:10");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt requestedDocumentIndex$LAYOUT = (OfInt)$LAYOUT.select(groupElement("requestedDocumentIndex"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int32_t requestedDocumentIndex
     * }
     */
    public static final OfInt requestedDocumentIndex$layout() {
        return requestedDocumentIndex$LAYOUT;
    }

    private static final long requestedDocumentIndex$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int32_t requestedDocumentIndex
     * }
     */
    public static final long requestedDocumentIndex$offset() {
        return requestedDocumentIndex$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int32_t requestedDocumentIndex
     * }
     */
    public static int requestedDocumentIndex(MemorySegment struct) {
        return struct.get(requestedDocumentIndex$LAYOUT, requestedDocumentIndex$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int32_t requestedDocumentIndex
     * }
     */
    public static void requestedDocumentIndex(MemorySegment struct, int fieldValue) {
        struct.set(requestedDocumentIndex$LAYOUT, requestedDocumentIndex$OFFSET, fieldValue);
    }

    private static final AddressLayout selectedDocumentIndex$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("selectedDocumentIndex"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int32_t *selectedDocumentIndex
     * }
     */
    public static final AddressLayout selectedDocumentIndex$layout() {
        return selectedDocumentIndex$LAYOUT;
    }

    private static final long selectedDocumentIndex$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int32_t *selectedDocumentIndex
     * }
     */
    public static final long selectedDocumentIndex$offset() {
        return selectedDocumentIndex$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int32_t *selectedDocumentIndex
     * }
     */
    public static MemorySegment selectedDocumentIndex(MemorySegment struct) {
        return struct.get(selectedDocumentIndex$LAYOUT, selectedDocumentIndex$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int32_t *selectedDocumentIndex
     * }
     */
    public static void selectedDocumentIndex(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(selectedDocumentIndex$LAYOUT, selectedDocumentIndex$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

